version: "3"
services:
  trainer:
    build: .
    container_name: maboroshi
    volumes:
      - ./weights:/app/st-gcn/weights
      - ./video:/app/st-gcn/video
      - ./output:/app/st-gcn/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
